#  eureka 服务治理的远程注册地址
global:
  nacos:
    server-addr: 127.0.0.1:8848
# 服务注册中心
quartz-center:
  name: quartz-center
  port: 8761
# 客户端
quartz-client:
  name: quartz-client
  port: 8081
# 服务端
quartz-server:
  name: quartz-server
  port: 8082
