spring:
  application:
    name: ${quartz-client.name}
  profiles:
    active: global
  cloud:
    nacos:
      discovery:
        server-addr: ${global.nacos.server-addr}
server:
  port: ${quartz-client.port}
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: warn
# 服务的名字
fixed:
  server:
    name: ${quartz-server.name}
